final_dir = [ ] # For example: ["/mnt/dst/00", "/mnt/dst/01"], The final directory will plot will saved.

[main]
work_dir = "./plotboss_data" #
# max_jobs = 10 # default is not set.

[[jobs]]
tmp_dir = "/mnt/tmp/00"
# tmp2_dir = "/mnt/tmp/01"
# max_jobs = 1
# job_start_mode = "simple"

# size = 32
# nobitfield = false
# farmer_key = ""
# pool_key = ""
# pool_address = ""
# num_threads = 2
# bukets = 128
# buffer = 4_608

[[jobs]]
tmp_dir = "/mnt/tmp/02"
# tmp2_dir = "/mnt/tmp/03"   # optional
# max_jobs = 1  # default is 1.

# size = 32
# nobitfield = false
# num_threads = 2
# bukets = 128
# buffer = 4_608